const DELETE_USER = "DELETE_USER";
const FETCH_USERS = "FETCH_USERS";
const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
const FETCH_PRODUCTS = "FETCH_PRODUCTS";
const ADD_TO_CART = "ADD_TO_CART";
const SET_CART_PRODUCTS = "ADD_CART_PRODUCTS";

export {
  DELETE_USER,
  FETCH_USERS,
  FETCH_USERS_FAILURE,
  FETCH_PRODUCTS,
  ADD_TO_CART,
  SET_CART_PRODUCTS,
};
